"""ScholarFlow 服务层子模块。

提供按职责拆分的 Mixin 类，由 ScholarService 组合继承。
"""

from .constants import (
    ANALYSIS_PROMPT,
    ARXIV_API_URL,
    ASSISTANT_PROMPT,
    CHALLENGE_PROMPT,
    CHALLENGE_STAGES,
    CHINESE_TO_ENGLISH_KEYWORDS,
    DEFAULT_DISCOVERY_CATALOG,
    PLAN_PROMPT,
    SEARCH_PROMPT,
    TRANSLATION_PROMPT,
    WRITING_PROMPT,
)
from .helpers import (
    build_catalog_content,
    build_search_links,
    ensure_reader_content,
    fallback_analysis,
    fallback_assistant,
    fallback_challenge_evaluation,
    fallback_plan,
    fallback_search_guide,
    fallback_writing,
    guess_abstract,
    guess_authors,
    guess_source,
    guess_title,
    guess_year,
    latest_attempt,
    normalize_challenge_score,
    now,
    notes_context,
    paper_context,
    rank_catalog,
    report_answer,
    safe_filename,
    split_sentences,
    stage_latest_attempt,
    stage_reference_answer,
    tokenize,
    with_challenge_progress,
)

__all__ = [
    "ANALYSIS_PROMPT",
    "ARXIV_API_URL",
    "ASSISTANT_PROMPT",
    "CHALLENGE_PROMPT",
    "CHALLENGE_STAGES",
    "CHINESE_TO_ENGLISH_KEYWORDS",
    "DEFAULT_DISCOVERY_CATALOG",
    "PLAN_PROMPT",
    "SEARCH_PROMPT",
    "TRANSLATION_PROMPT",
    "WRITING_PROMPT",
    "build_catalog_content",
    "build_search_links",
    "ensure_reader_content",
    "fallback_analysis",
    "fallback_assistant",
    "fallback_challenge_evaluation",
    "fallback_plan",
    "fallback_search_guide",
    "fallback_writing",
    "guess_abstract",
    "guess_authors",
    "guess_source",
    "guess_title",
    "guess_year",
    "latest_attempt",
    "normalize_challenge_score",
    "now",
    "notes_context",
    "paper_context",
    "rank_catalog",
    "report_answer",
    "safe_filename",
    "split_sentences",
    "stage_latest_attempt",
    "stage_reference_answer",
    "tokenize",
    "with_challenge_progress",
]
